[project]
name = "linkedin-gold-compound-simple"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.9.0",
    "pip>=26.0",
    "polars>=1.37.1",
    "typst>=0.14.7",
]
